#include<bits/stdc++.h>
using namespace std;
int main()
{
    int a,b,c,i,j;
    string s,x;
    while(getline(cin,s))
    {
        x[0]=39;
        a=s.size();
        for(i=0;i<a;i++)
        {
            if(s[i]==']'||s[i]=='}')
            {
                cout<<"p";
            }
             if(s[i]=='['||s[i]=='{')
            {
                cout<<"o";
            }
             if(s[i]=='p'||s[i]=='P')
            {
                cout<<"i";
            }
             if(s[i]=='o'||s[i]=='O')
            {
                cout<<"u";
            }
             if(s[i]=='i'||s[i]=='I')
            {
                cout<<"y";
            }
             if(s[i]=='u'||s[i]=='U')
            {
                cout<<"t";
            }
             if(s[i]=='y'||s[i]=='Y')
            {
                cout<<"r";
            }
             if(s[i]=='t'||s[i]=='T')
            {
                cout<<"e";
            }
            if(s[i]=='r'||s[i]=='R')
            {
                cout<<"w";
            }
            if(s[i]=='E'||s[i]=='e')
            {
                cout<<"q";
            }
             if(s[i]==';'||s[i]==':')
            {
                cout<<"k";
            }
             if(s[i]=='L'||s[i]=='l')
            {
                cout<<"j";
            }
             if(s[i]=='k'||s[i]=='K')
            {
                cout<<"h";
            }
             if(s[i]=='J'||s[i]=='j')
            {
                cout<<"g";
            }
             if(s[i]==x[0])
            {
                cout<<"l";
            }
             if(s[i]=='H'||s[i]=='h')
            {
                cout<<"f";
            }
             if(s[i]=='G'||s[i]=='g')
            {
                cout<<"d";
            }
             if(s[i]=='F'||s[i]=='f')
            {
                cout<<"s";
            }
             if(s[i]=='d'||s[i]=='D')
            {
                cout<<"a";
            }
             if(s[i]=='>'||s[i]=='.')
            {
                cout<<"m";
            }
             if(s[i]=='<'||s[i]==',')
            {
                cout<<"n";
            }
             if(s[i]=='M'||s[i]=='m')
            {
                cout<<"b";
            }
             if(s[i]=='N'||s[i]=='n')
            {
                cout<<"v";
            }
             if(s[i]=='B'||s[i]=='b')
            {
                cout<<"c";
            }
             if(s[i]=='V'||s[i]=='v')
            {
                cout<<"x";
            }
             if(s[i]=='C'||s[i]=='c')
            {
                cout<<"z";
            }
            if(s[i]==' ')
            {
                cout<<" ";
            }

        }
    }
    return 0;
}
